import * as v from 'valibot'
import { parse, stringify } from 'yaml'

import type { BunderstackManifest } from './manifest'

import { parseCron } from './jobs/cron'
import { validateStandardSchema } from './standard-schema'

export type MigrationMode = 'migrations' | 'push'
export type ApplicationFramework =
  | 'tanstack-start'
  | 'solid'
  | 'bun-ssr'
  | 'custom'

/**
 * Blueprint form of an environment key. `sensitive` and `description` are
 * optional because blueprints committed before 0.23.0 do not carry them.
 */
export type BlueprintEnvVar = {
  key: string
  required: boolean
  scope: 'server' | 'client'
  sensitive?: boolean
  description?: string
}

export const WORKER_PACKAGE_ENTRIES = [
  'bunderstack/start/server-entry',
  'bunderstack/workers/entry',
] as const
export type WorkerRender = 'ssr' | 'spa'

export type WorkerSettings = {
  render: WorkerRender
  /** A relative path inside the package, or one of WORKER_PACKAGE_ENTRIES. */
  main: string
  compatibilityDate: string
  assets: string
}

type BlueprintBackground = Pick<
  BunderstackManifest['background'],
  'jobs' | 'cron' | 'maintenance'
>

type BlueprintBody = {
  generator: { name: 'bunderstack'; version: string }
  bunderstack: { entry: string; manifestVersion: 4 }
  resources: {
    database: BunderstackManifest['database'] & { migrationMode: MigrationMode }
    storage: BunderstackManifest['storage']
    realtime?: { required: true }
    messaging: BunderstackManifest['messaging']
  }
  environment: BlueprintEnvVar[]
  /** Application-declared procedures. Absent in blueprints written before 0.23.0. */
  api?: { operations: BunderstackManifest['api']['operations'] }
}

/** The 0.x server contract. Parsed for hosts; never generated by 1.0. */
export type LegacyBlueprint = BlueprintBody & {
  version: 1
  application: {
    framework: ApplicationFramework
    scripts: { build: 'build'; start: 'start'; worker?: 'worker' }
  }
  background: BlueprintBackground & { worker: { required: boolean } }
}

/** The 1.0 Worker contract. */
export type WorkerBlueprint = BlueprintBody & {
  version: 2
  application: {
    framework: ApplicationFramework
    scripts: { build: 'build' }
    worker: WorkerSettings
  }
  background: BlueprintBackground
}

export type BunderstackBlueprint = LegacyBlueprint | WorkerBlueprint

const nonEmpty = v.pipe(v.string(), v.minLength(1))
const relativePath = v.pipe(
  nonEmpty,
  v.check(
    (value) =>
      !value.startsWith('/') &&
      !value.includes('\\') &&
      value.split('/').every((part) => part !== '' && part !== '..'),
    'entry must be a relative path without traversal',
  ),
)
const cronSchedule = v.pipe(
  nonEmpty,
  v.check((value) => {
    try {
      parseCron(value)
      return true
    } catch {
      return false
    }
  }, 'invalid cron schedule'),
)

// Hosts parse blueprints committed by applications that upgrade bunderstack on
// their own schedule, so a section written by a newer generator has to survive
// an older parser instead of failing the whole file.
function open<TEntries extends v.ObjectEntries>(entries: TEntries) {
  return v.objectWithRest(entries, v.unknown())
}

const compatibilityDate = v.pipe(
  v.string(),
  v.regex(/^\d{4}-\d{2}-\d{2}$/, 'compatibilityDate must be YYYY-MM-DD'),
)
const workerMain = v.pipe(
  nonEmpty,
  v.check(
    (value) =>
      (WORKER_PACKAGE_ENTRIES as readonly string[]).includes(value) ||
      (!value.startsWith('bunderstack/') &&
        !value.startsWith('@') &&
        !value.startsWith('/') &&
        !value.includes('\\') &&
        value.split('/').every((part) => part !== '' && part !== '..')),
    'main must be a relative path inside the package or a bunderstack entry',
  ),
)
const framework = v.picklist(['tanstack-start', 'solid', 'bun-ssr', 'custom'])

const generatorEntry = open({
  name: v.literal('bunderstack'),
  version: nonEmpty,
})

const sharedEntries = {
  bunderstack: open({
    entry: relativePath,
    manifestVersion: v.literal(4),
  }),
  resources: open({
    database: open({
      dialect: v.picklist(['sqlite']),
      migrationsDirectory: relativePath,
      migrationMode: v.picklist(['migrations', 'push']),
      tables: v.array(
        open({
          exportName: nonEmpty,
          physicalName: nonEmpty,
          system: v.boolean(),
        }),
      ),
    }),
    storage: open({
      defaultBucket: nonEmpty,
      buckets: v.array(
        open({
          name: nonEmpty,
          visibility: v.picklist(['public', 'private']),
        }),
      ),
    }),
    realtime: v.optional(open({ required: v.literal(true) })),
    messaging: open({
      channels: v.array(
        open({ name: nonEmpty, kind: nonEmpty, provider: nonEmpty }),
      ),
    }),
  }),
  environment: v.array(
    open({
      key: nonEmpty,
      required: v.boolean(),
      scope: v.picklist(['server', 'client']),
      sensitive: v.optional(v.boolean()),
      description: v.optional(v.pipe(nonEmpty, v.maxLength(200))),
    }),
  ),
  api: v.optional(
    open({
      operations: v.array(
        open({
          handle: nonEmpty,
          operationId: nonEmpty,
          effect: v.picklist(['read', 'mutation', 'unknown']),
          method: v.optional(nonEmpty),
          path: v.optional(nonEmpty),
          summary: v.optional(v.pipe(nonEmpty, v.maxLength(200))),
        }),
      ),
    }),
  ),
}

const backgroundEntries = {
  jobs: v.array(open({ name: nonEmpty })),
  cron: v.array(
    open({
      name: nonEmpty,
      schedule: cronSchedule,
      timezone: v.literal('UTC'),
    }),
  ),
  maintenance: v.array(
    open({
      name: v.literal('storage-sweep'),
      schedule: cronSchedule,
      timezone: v.literal('UTC'),
    }),
  ),
}

const legacySchema = open({
  version: v.literal(1),
  // Key order is the YAML order: identity and application first.
  generator: generatorEntry,
  application: open({
    framework,
    scripts: open({
      build: v.literal('build'),
      start: v.literal('start'),
      worker: v.optional(v.literal('worker')),
    }),
  }),
  ...sharedEntries,
  background: open({
    worker: open({ required: v.boolean() }),
    ...backgroundEntries,
  }),
})

const workerSchema = open({
  version: v.literal(2),
  // Key order is the YAML order: identity and application first.
  generator: generatorEntry,
  application: open({
    framework,
    scripts: open({ build: v.literal('build') }),
    worker: open({
      render: v.picklist(['ssr', 'spa']),
      main: workerMain,
      compatibilityDate,
      assets: relativePath,
    }),
  }),
  ...sharedEntries,
  background: open(backgroundEntries),
})

const blueprintSchema = v.variant('version', [legacySchema, workerSchema])

function sortBy<T>(entries: readonly T[], key: (entry: T) => string): T[] {
  return [...entries].sort((left, right) => key(left).localeCompare(key(right)))
}

function rejectDuplicates(collection: string, values: readonly string[]): void {
  const seen = new Set<string>()
  for (const value of values) {
    if (seen.has(value))
      throw new Error(`[bunderstack] duplicate ${collection} "${value}"`)
    seen.add(value)
  }
}

export function parseBlueprint(value: unknown): BunderstackBlueprint {
  const raw = value as {
    version?: unknown
    application?: { runtime?: unknown }
  } | null
  if (raw?.version === 1 && raw.application?.runtime === 'worker') {
    throw new Error(
      '[bunderstack] this version 1 blueprint declares runtime: worker; regenerate the blueprint with bunderstack 1.0.0-beta.3',
    )
  }
  const worker = (
    raw?.application as { worker?: { render?: unknown } } | undefined
  )?.worker
  if (raw?.version === 2 && worker && worker.render === undefined) {
    throw new Error(
      '[bunderstack] application.worker.render is missing; regenerate the blueprint with bunderstack 1.0.0-beta.4',
    )
  }
  const blueprint = validateStandardSchema(
    blueprintSchema,
    value,
    'blueprint',
  ) as BunderstackBlueprint
  rejectDuplicates(
    'database physical table',
    blueprint.resources.database.tables.map((entry) => entry.physicalName),
  )
  rejectDuplicates(
    'database export table',
    blueprint.resources.database.tables.map((entry) => entry.exportName),
  )
  rejectDuplicates(
    'storage bucket',
    blueprint.resources.storage.buckets.map((entry) => entry.name),
  )
  rejectDuplicates(
    'environment key',
    blueprint.environment.map((entry) => entry.key),
  )
  rejectDuplicates(
    'messaging channel',
    blueprint.resources.messaging.channels.map((entry) => entry.name),
  )
  if (blueprint.api)
    rejectDuplicates(
      'api operation',
      blueprint.api.operations.map((entry) => entry.handle),
    )
  rejectDuplicates(
    'background job',
    blueprint.background.jobs.map((entry) => entry.name),
  )
  rejectDuplicates(
    'background cron',
    blueprint.background.cron.map((entry) => entry.name),
  )
  rejectDuplicates(
    'background maintenance',
    blueprint.background.maintenance.map((entry) => entry.name),
  )
  if (
    !blueprint.resources.storage.buckets.some(
      (bucket) => bucket.name === blueprint.resources.storage.defaultBucket,
    )
  ) {
    throw new Error(
      '[bunderstack] storage defaultBucket must be declared in storage buckets',
    )
  }
  if (blueprint.version === 1) {
    const workerRequired = blueprint.background.jobs.length > 0
    if (blueprint.background.worker.required !== workerRequired) {
      throw new Error(
        '[bunderstack] background worker.required must match declared queue jobs',
      )
    }
    if (Boolean(blueprint.application.scripts.worker) !== workerRequired) {
      throw new Error(
        '[bunderstack] application worker script must match declared queue jobs',
      )
    }
  } else {
    const scripts = blueprint.application.scripts as Record<string, unknown>
    if (Object.keys(scripts).some((name) => name !== 'build')) {
      throw new Error(
        '[bunderstack] a version 2 blueprint declares only the build script',
      )
    }
  }
  return blueprint
}

export function parseWorkerBlueprint(value: unknown): WorkerBlueprint {
  const blueprint = parseBlueprint(value)
  if (blueprint.version !== 2) {
    throw new Error(
      '[bunderstack] bunderstack.blueprint.yaml is a 0.x (version 1) blueprint; run `bunderstack dev` or `bunderstack blueprint` to regenerate it for 1.0',
    )
  }
  return blueprint
}

/**
 * Whether a host must treat this key as a secret. A blueprint generated before
 * 0.23.0 has no flag, and server keys are secret by default.
 */
export function isSensitiveEnvVar(entry: BlueprintEnvVar): boolean {
  return entry.sensitive ?? entry.scope === 'server'
}

export function blueprintFromManifest(args: {
  manifest: BunderstackManifest
  generatorVersion: string
  entry: string
  migrationMode: MigrationMode
  framework?: ApplicationFramework
  worker: WorkerSettings
}): WorkerBlueprint {
  return parseWorkerBlueprint({
    version: 2,
    generator: { name: 'bunderstack', version: args.generatorVersion },
    application: {
      framework: args.framework ?? 'tanstack-start',
      scripts: { build: 'build' },
      worker: args.worker,
    },
    bunderstack: { entry: args.entry, manifestVersion: 4 },
    resources: {
      database: {
        ...args.manifest.database,
        migrationMode: args.migrationMode,
        tables: sortBy(
          args.manifest.database.tables,
          (entry) => entry.physicalName,
        ),
      },
      storage: {
        ...args.manifest.storage,
        buckets: sortBy(args.manifest.storage.buckets, (entry) => entry.name),
      },
      ...(args.manifest.realtime.required
        ? { realtime: { required: true } }
        : {}),
      messaging: {
        channels: sortBy(
          args.manifest.messaging.channels,
          (entry) => entry.name,
        ),
      },
    },
    environment: sortBy(args.manifest.environment, (entry) => entry.key),
    api: { operations: args.manifest.api.operations },
    background: {
      jobs: sortBy(args.manifest.background.jobs, (entry) => entry.name),
      cron: sortBy(args.manifest.background.cron, (entry) => entry.name),
      maintenance: sortBy(
        args.manifest.background.maintenance,
        (entry) => entry.name,
      ),
    },
  })
}

export function parseBlueprintYaml(source: string): BunderstackBlueprint {
  return parseBlueprint(parse(source) as unknown)
}

export function parseWorkerBlueprintYaml(source: string): WorkerBlueprint {
  return parseWorkerBlueprint(parse(source) as unknown)
}

export function serializeBlueprint(value: BunderstackBlueprint): string {
  const blueprint = parseBlueprint(value)
  const options = {
    aliasDuplicateObjects: false,
    defaultKeyType: 'PLAIN',
    defaultStringType: 'PLAIN',
    lineWidth: 0,
  } as const
  const source = stringify(
    parseBlueprintYaml(stringify(blueprint, options)),
    options,
  )
  return source.replace(
    /^(\s*schedule: )(.+)$/gm,
    (_match, prefix: string, value: string) => {
      const schedule = value.startsWith('"') ? JSON.parse(value) : value
      return `${prefix}${JSON.stringify(schedule)}`
    },
  )
}

export {
  bucketBindingName,
  workerPlanFromBlueprint,
  type WorkerPlan,
} from './worker-plan'
